AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'config/**/*'

require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Exclude:
    - spec/shared/**/*.rb

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/MissingSuper:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Exclude:
    - spec/shared/**/*.rb